trigger:
- main # Pipeline will trigger on changes to the main branch

pool:
  name: 'MySelfHostedPool' # Replace with your self-hosted agent pool name

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x' # Specify the .NET SDK version for your project

- script: dotnet build
  displayName: 'Build the Application'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish the Application'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: 'drop'
    publishLocation: 'Container'
